# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bullseye"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bullseye"
  armhf: "ghcr.io/home-assistant/armhf-base-debian:bullseye"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:bullseye"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: TensorFlow Pet Feeder"
  org.opencontainers.image.description: "Home Assistant add-on to automate pet feeding."
  org.opencontainers.image.source: "https://github.com/uncle-yura/tf-pet-feeder"
  org.opencontainers.image.licenses: "Apache License 2.0"
